language: python
sudo: false
before_script:
  - pip install tox
script:
  - tox
matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=docstrings
  include:
    - arch: arm64
      python: 2.7
      env: TOXENV=py27
    - arch: amd64
      python: 2.7
      env: TOXENV=py27
    - arch: arm64
      python: 3.4
      env: TOXENV=py34
    - arch: amd64
      python: 3.4
      env: TOXENV=py34
    - arch: arm64
      python: 3.5
      env: TOXENV=py35
    - arch: amd64
      python: 3.5
      env: TOXENV=py35
    - arch: arm64
      python: 3.6
      env: TOXENV=py36
    - arch: amd64
      python: 3.6
      env: TOXENV=py36
    - arch: arm64
      python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - arch: amd64
      python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - arch: amd64
      python: pypy
      env: TOXENV=pypy
    - arch: arm64
      env: TOXENV=docstrings
    - arch: amd64
      env: TOXENV=docstrings
    - arch: arm64
      env: TOXENV=flake8
    - arch: amd64
      env: TOXENV=flake8

notifications:
  irc:
    channels:
      - "irc.freenode.org##python-code-quality"
    use_notice: true
    skip_join: true
